version: '3.1'

services:
  db:
    image: mysql:8.0.21
    container_name: app-users
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234567
    restart: 'always'
